create table cliente (id bigint not null auto_increment, cpf varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table empresa (saldo decimal(38,2), taxa_sistema decimal(38,2), id bigint not null auto_increment, cnpj varchar(255), nome varchar(255), primary key (id)) engine=InnoDB;
create table transacao (tipo_transacao tinyint check (tipo_transacao between 0 and 1), valor decimal(38,2), valor_taxa decimal(38,2), cliente_id bigint, data_hora datetime(6), empresa_id bigint, id bigint not null auto_increment, primary key (id)) engine=InnoDB;
alter table transacao add constraint FKk44khwkynm4lmqa4ewiaaprdb foreign key (cliente_id) references cliente (id);
alter table transacao add constraint FKef4s7vpl4107mh6ccjbvqgaeu foreign key (empresa_id) references empresa (id);
INSERT INTO cliente(nome, cpf) VALUES ('Josefa Barbosa', '234567809');
INSERT INTO cliente(nome, cpf) VALUES ('Otávio Mesquita', '234657812');
INSERT INTO empresa(nome, cnpj) VALUES ('Mercado Samambaia', '232134/0001');
INSERT INTO empresa(nome, cnpj) VALUES ('Mecânica Pit Stop', '452144/0001');
INSERT INTO transacao(empresa_id, cliente_id, valor, tipo_transacao, valor_taxa) VALUES (1, 2, 100.0, 0, 0.1);
INSERT INTO transacao(empresa_id, cliente_id, valor, tipo_transacao, valor_taxa) VALUES (2, 1, 1500.0, 1, 0.1);
INSERT INTO transacao(empresa_id, cliente_id, valor, tipo_transacao, valor_taxa) VALUES (1, 1, 300.0, 1, 0.1);
